CREATE TABLE K_CONTRACT_EXTEND_CX
(
"POLICY_CHG_ID" NUMBER(19,0) NOT NULL, 
	"ITEM_ID" NUMBER(19,0) NOT NULL, 
	"POLICY_ID" NUMBER(19,0) NOT NULL, 
	"CHANGE_ID" NUMBER(19,0) NOT NULL, 
	"LOG_ID" NUMBER(19,0), 
	"PRE_LOG_ID" NUMBER(19,0), 
	"OPER_TYPE" VARCHAR2(1 BYTE), 
	"LOG_TYPE" CHAR(1 BYTE) DEFAULT '1' NOT NULL, 
	"CHANGE_SEQ" NUMBER(15,3), 
	 CONSTRAINT "PK_K_CONTRACT_EXTEND_CX" PRIMARY KEY ("POLICY_CHG_ID", "ITEM_ID")
)