BEGIN
	execute immediate 'ALTER TABLE "K_POLICY_CHANGE" ADD CONSTRAINT "K_POLICY_CHANGE_X" PRIMARY KEY ("POLICY_CHG_ID")';
	execute immediate 'CREATE INDEX "K_POLICY_CHANGE_IDXFT" ON "K_POLICY_CHANGE" ("FINISH_TIME")';
	execute immediate 'CREATE INDEX "K_POLICY_CHANGE_IDXMA" ON "K_POLICY_CHANGE" ("MASTER_CHG_ID")';
	execute immediate 'CREATE INDEX "K_POLICY_CHANGE_IDXPI" ON "K_POLICY_CHANGE" ("POLICY_ID")';
	execute immediate 'CREATE INDEX "K_POLICY_CHANGE_IDXVT" ON "K_POLICY_CHANGE" ("VALIDATE_TIME")';
END;	
