BEGIN
	execute immediate 'ALTER TABLE "K_SUPPL_LOG_SYNC" ADD CONSTRAINT "K_SUPPL_LOG_SYNC_X" PRIMARY KEY ("RS_ID","SSN")';
	execute immediate 'CREATE INDEX "K_SUPPL_LOG_SYNC_IDXSCN" ON "K_SUPPL_LOG_SYNC" ("SCN")';
	execute immediate 'CREATE INDEX "K_SUPPL_LOG_SYNC_IDXTIME" ON "K_SUPPL_LOG_SYNC" ("INSERT_TIME")';
END;	
