BEGIN
	execute immediate 'ALTER TABLE "SUPPL_LOG_SYNC" ADD CONSTRAINT "SUPPL_LOG_SYNC_X" PRIMARY KEY ("RS_ID","SSN")';
	execute immediate 'CREATE INDEX "SUPPL_LOG_SYNC_IDXSCN" ON "SUPPL_LOG_SYNC" ("SCN")';
	execute immediate 'CREATE INDEX "SUPPL_LOG_SYNC_IDTAB" ON "SUPPL_LOG_SYNC" ("TABLE_NAME")';
	execute immediate 'CREATE INDEX "SUPPL_LOG_SYNC_IDXTIME" ON "SUPPL_LOG_SYNC" ("INSERT_TIME")';
END;	
