BEGIN
	execute immediate 'CREATE INDEX "K_PRODUCT_COMMISION_IDXI" ON "K_PRODUCT_COMMISION" ("ITEM_ID")';
	execute immediate 'CREATE UNIQUE INDEX "K_PRODUCT_COMMISION_ETL" ON "K_PRODUCT_COMMISION" ("SCN","COMMIT_SCN","ROW_ID")';
END;	
