BEGIN
	execute immediate 'ALTER TABLE "K_CONTRACT_EXTEND_CX" ADD CONSTRAINT "K_CONTRACT_EXTEND_CX_X" PRIMARY KEY ("POLICY_CHG_ID", "ITEM_ID")';
  	execute immediate 'CREATE UNIQUE INDEX "K_CONTRACT_EXTEND_CX_ETL" ON "K_CONTRACT_EXTEND_CX" ("SCN","COMMIT_SCN","ROW_ID")';
END;	 
