BEGIN
	execute immediate 'CREATE INDEX "IDX_PRODUCTION_DETAIL_CII" ON "K_PRODUCTION_DETAIL" ("COMM_ITEM_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCTION_DETAIL__AGGREG1" ON "K_PRODUCTION_DETAIL" ("AGGREGATION_ID", "PRODUCER_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCTION_DETAIL__POLICY1" ON "K_PRODUCTION_DETAIL" ("POLICY_CHG_ID", "PRODUCTION_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCTION_DETAIL__RELATED" ON "K_PRODUCTION_DETAIL" ("RELATED_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCTION_DETAIL__RESULT_" ON "K_PRODUCTION_DETAIL" ("RESULT_LIST_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETAIL_YM_AG" ON "K_PRODUCTION_DETAIL" ("YEAR_MONTH", "PRODUCER_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETAIL_YM_CH" ON "K_PRODUCTION_DETAIL" ("YEAR_MONTH", "CHANNEL_ORG_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETAIL__AGENT_CHANNEL" ON "K_PRODUCTION_DETAIL" ("AGENT_CATE", "CHANNEL_ORG_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETAIL__POLICY_ID" ON "K_PRODUCTION_DETAIL" ("POLICY_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETAIL__PRODUCER_ID" ON "K_PRODUCTION_DETAIL" ("PRODUCER_ID", "EFFECTIVE_DATE")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETIAL__CHEQUE_CATE" ON "K_PRODUCTION_DETAIL" ("CHEQUE_INDI", "AGENT_CATE")';
	execute immediate 'CREATE INDEX "IDX_PROD_DETIAL__ITEM_ID" ON "K_PRODUCTION_DETAIL" ("ITEM_ID")';
END;	