BEGIN
  execute immediate 'CREATE INDEX "IDX_COMMISION_FEE_CHEQUE_ID" ON "K_COMMISION_FEE" ("CHEQUE_ID")';
  execute immediate 'CREATE INDEX "IDX_COMMISION_FEE__POSTED__HAP" ON "K_COMMISION_FEE" ("POSTED", "HAPPEN_TIME")' ;
END;