BEGIN
  execute immediate 'CREATE INDEX "K_COMMISION_FEE_IDXF" ON "K_COMMISION_FEE" ("FEE_ID")';
  execute immediate 'CREATE UNIQUE INDEX "K_COMMISSION_FEE_ETL" ON "K_COMMISION_FEE" ("SCN","COMMIT_SCN","ROW_ID")');
END;
