BEGIN
	execute immediate 'CREATE INDEX "IDX_PPJ__POLICY_ID" ON "K_POLICY_PRINT_JOB" ("POLICY_ID")';
	execute immediate 'CREATE INDEX "IDX_PPJ__PRI_COMP_I_PRI_CATE" ON "K_POLICY_PRINT_JOB" ("PRINT_COMP_INDI", "PRINT_CATEGORY")';
END;	