BEGIN
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__AGGREGA" ON "K_PRODUCT_COMMISION" ("AGGREGATION_ID", "AGENT_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__BENEFIT" ON "K_PRODUCT_COMMISION" ("BENEFIT_ITEM_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__COMM_ID" ON "K_PRODUCT_COMMISION" ("COMMISION_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__HAPPEN_" ON "K_PRODUCT_COMMISION" ("HAPPEN_TIME", "COMMISION_TYPE_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__RELATE" ON "K_PRODUCT_COMMISION" ("RELATED_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__RESULT_" ON "K_PRODUCT_COMMISION" ("RESULT_LIST_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__REVERSA" ON "K_PRODUCT_COMMISION" ("REVERSAL_POLICY_CHG_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COMMISION__YEAR_MO" ON "K_PRODUCT_COMMISION" ("YEAR_MONTH")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COM__LIST_ID_AGENT" ON "K_PRODUCT_COMMISION" ("LIST_ID", "AGENT_ID")';
	execute immediate 'CREATE INDEX "IDX_PRODUCT_COM__POLICY_ID" ON "K_PRODUCT_COMMISION" ("POLICY_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_COMM__CHANGE_ID" ON "K_PRODUCT_COMMISION" ("CHANGE_ID")';
	execute immediate 'CREATE INDEX "IDX_PROD_COMM__CHEQUE_CATE" ON "K_PRODUCT_COMMISION" ("CHEQUE_INDI", "AGENT_CATE")';
	execute immediate 'CREATE INDEX "IDX_PROD_COMM__POLICY_CHG_ID" ON "K_PRODUCT_COMMISION" ("POLICY_CHG_ID")';
END;	