BEGIN
	execute immediate 'CREATE INDEX "IDX_CONTRACT_EXTEND_L__D_DATE" ON "K_CONTRACT_EXTEND_LOG" ("DUE_DATE")';
	execute immediate 'CREATE INDEX "IDX_CONTRACT_EXTEND_L__LAST_CM" ON "K_CONTRACT_EXTEND_LOG" ("LAST_CMT_FLG", "ITEM_ID")';
	execute immediate 'CREATE INDEX "IDX_CONTRACT_EXTEND_L__POL_FLG" ON "K_CONTRACT_EXTEND_LOG" ("POLICY_ID", "LAST_CMT_FLG")'; 
	execute immediate 'ALTER TABLE "K_CONTRACT_EXTEND_LOG" ADD CONSTRAINT "UNI_CONTRACT_EXTEND_LOG__ID" UNIQUE ("POLICY_CHG_ID", "ITEM_ID", "LOG_TYPE")';
END;