BEGIN
	execute immediate 'CREATE INDEX "IDX_VARINST_NAME_LONG" ON "K_JBPM_VARIABLEINSTANCE" ("NAME_", "LONGVALUE_")';
	execute immediate 'CREATE INDEX "IDX_VARINST_NAME_STRING" ON "K_JBPM_VARIABLEINSTANCE" ("NAME_", "STRINGVALUE_")';
	execute immediate 'CREATE INDEX "IDX_VARINST_PROCINST" ON "K_JBPM_VARIABLEINSTANCE" ("PROCESSINSTANCE_")';
	execute immediate 'CREATE INDEX "IDX_VARINST_TASKINS" ON "K_JBPM_VARIABLEINSTANCE" ("TASKINSTANCE_")';
	execute immediate 'CREATE INDEX "IDX_VARINST_TKVARMP" ON "K_JBPM_VARIABLEINSTANCE" ("TOKENVARIABLEMAP_")';
	execute immediate 'CREATE INDEX "IDX__LONGVALUE_" ON "K_JBPM_VARIABLEINSTANCE" ("LONGVALUE_")';
	execute immediate 'CREATE INDEX "IDX__STRINGVALUE_" ON "K_JBPM_VARIABLEINSTANCE" ("STRINGVALUE_")';
END;	