-- for K_COMMISION_FEE
CREATE INDEX "IDX_COMMISION_FEE_CHEQUE_ID" ON "K_COMMISION_FEE" ("CHEQUE_ID");
CREATE INDEX "IDX_COMMISION_FEE__POSTED__HAP" ON "K_COMMISION_FEE" ("POSTED", "HAPPEN_TIME") ;

-- for K_CONTRACT_EXTEND_CX
CREATE INDEX "IDX_CONT_EXTE_CX__OPER_TYPE" ON "K_CONTRACT_EXTEND_CX" ("CHANGE_ID", "OPER_TYPE");
CREATE INDEX "I_CONTRACT_EXTEND_CX__LOG_ID" ON "K_CONTRACT_EXTEND_CX" ("LOG_ID");

-- for K_CONTRACT_EXTEND_LOG
CREATE INDEX "IDX_CONTRACT_EXTEND_L__D_DATE" ON "K_CONTRACT_EXTEND_LOG" ("DUE_DATE");
CREATE INDEX "IDX_CONTRACT_EXTEND_L__LAST_CM" ON "K_CONTRACT_EXTEND_LOG" ("LAST_CMT_FLG", "ITEM_ID");
CREATE INDEX "IDX_CONTRACT_EXTEND_L__POL_FLG" ON "K_CONTRACT_EXTEND_LOG" ("POLICY_ID", "LAST_CMT_FLG"); 
ALTER TABLE "K_CONTRACT_EXTEND_LOG" ADD CONSTRAINT "UNI_CONTRACT_EXTEND_LOG__ID" UNIQUE ("POLICY_CHG_ID", "ITEM_ID", "LOG_TYPE");

-- for K_CONTRACT_PRODUCT_LOG
CREATE INDEX "IDX_CONTRACT_PRODUCT_L__LAST_C" ON "K_CONTRACT_PRODUCT_LOG" ("LAST_CMT_FLG", "ITEM_ID");
CREATE INDEX "IDX_CONTRACT_PRODUCT_L__L_POL" ON "K_CONTRACT_PRODUCT_LOG" ("LAST_CMT_FLG", "POLICY_ID");
CREATE INDEX "IDX_CONTR_PRD_LOG_MAST_WAIVE" ON "K_CONTRACT_PRODUCT_LOG" ("MASTER_ID", "WAIVER");
ALTER TABLE "K_CONTRACT_PRODUCT_LOG" ADD CONSTRAINT "UNI_CONTRACT_PRODUCT_LOG__ID" UNIQUE ("POLICY_CHG_ID", "ITEM_ID", "LOG_TYPE");

-- for K_IMAGE
CREATE INDEX "IDX_IMAGE_AUTH_CODE" ON "K_IMAGE" ("AUTH_CODE");
CREATE INDEX "IDX_IMAGE_LIST_ID" ON "K_IMAGE" ("LIST_ID");
CREATE INDEX "IDX_IMAGE__BOX_NO" ON "K_IMAGE" ("BOX_NO");
CREATE INDEX "IDX_IMAGE__CASE_ID" ON "K_IMAGE" ("CASE_ID");
CREATE INDEX "IDX_IMAGE__CHANGE_DI" ON "K_IMAGE" ("CHANGE_ID");
CREATE INDEX "IDX_IMAGE__FILE_CODE" ON "K_IMAGE" ("FILE_CODE") ;
CREATE INDEX "IDX_IMAGE__GRP_POLICY_ID" ON "K_IMAGE" ("GROUP_POLICY_ID");
CREATE INDEX "IDX_IMAGE__POLICY_ID" ON "K_IMAGE" ("POLICY_ID");
CREATE INDEX "IDX_IMAGE__SCAN_TIME" ON "K_IMAGE" ("SCAN_TIME", "IMAGE_TYPE_ID"); 

-- for K_JBPM_VARIABLEINSTANCE
CREATE INDEX "IDX_VARINST_NAME_LONG" ON "K_JBPM_VARIABLEINSTANCE" ("NAME_", "LONGVALUE_");
CREATE INDEX "IDX_VARINST_NAME_STRING" ON "K_JBPM_VARIABLEINSTANCE" ("NAME_", "STRINGVALUE_");
CREATE INDEX "IDX_VARINST_PROCINST" ON "K_JBPM_VARIABLEINSTANCE" ("PROCESSINSTANCE_");
CREATE INDEX "IDX_VARINST_TASKINS" ON "K_JBPM_VARIABLEINSTANCE" ("TASKINSTANCE_");
CREATE INDEX "IDX_VARINST_TKVARMP" ON "K_JBPM_VARIABLEINSTANCE" ("TOKENVARIABLEMAP_");
CREATE INDEX "IDX__LONGVALUE_" ON "K_JBPM_VARIABLEINSTANCE" ("LONGVALUE_");
CREATE INDEX "IDX__STRINGVALUE_" ON "K_JBPM_VARIABLEINSTANCE" ("STRINGVALUE_");

-- for K_POLICY_CHANGE
CREATE INDEX "IDX_PC__INSERT_TIME_SERVI" ON "K_POLICY_CHANGE" ("SERVICE_ID", "INSERT_TIME") ;
CREATE INDEX "IDX_PC__VALIDATE_TIME_SER" ON "K_POLICY_CHANGE" ("SERVICE_ID", "VALIDATE_TIME");
CREATE INDEX "IDX_POLICY_CHANGE__FINISH_TIME" ON "K_POLICY_CHANGE" ("SERVICE_ID", "FINISH_TIME");
CREATE INDEX "IDX_POLICY_CHANGE__POLICY_SEQ" ON "K_POLICY_CHANGE" ("POLICY_ID", "CHANGE_SEQ");
CREATE INDEX "IDX_POLICY_CHANGE__PRE_POLICY_" ON "K_POLICY_CHANGE" ("PRE_POLICY_CHG");
CREATE INDEX "IDX_POL_CHANGE__MASTER_CHG_ID" ON "K_POLICY_CHANGE" ("MASTER_CHG_ID");

-- for K_POLICY_PRINT_JOB
CREATE INDEX "IDX_PPJ__POLICY_ID" ON "K_POLICY_PRINT_JOB" ("POLICY_ID");
CREATE INDEX "IDX_PPJ__PRI_COMP_I_PRI_CATE" ON "K_POLICY_PRINT_JOB" ("PRINT_COMP_INDI", "PRINT_CATEGORY");

-- for K_PRODUCT_COMMISION
CREATE INDEX "IDX_PRODUCT_COMMISION__AGGREGA" ON "K_PRODUCT_COMMISION" ("AGGREGATION_ID", "AGENT_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__BENEFIT" ON "K_PRODUCT_COMMISION" ("BENEFIT_ITEM_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__COMM_ID" ON "K_PRODUCT_COMMISION" ("COMMISION_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__HAPPEN_" ON "K_PRODUCT_COMMISION" ("HAPPEN_TIME", "COMMISION_TYPE_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__RELATE" ON "K_PRODUCT_COMMISION" ("RELATED_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__RESULT_" ON "K_PRODUCT_COMMISION" ("RESULT_LIST_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__REVERSA" ON "K_PRODUCT_COMMISION" ("REVERSAL_POLICY_CHG_ID");
CREATE INDEX "IDX_PRODUCT_COMMISION__YEAR_MO" ON "K_PRODUCT_COMMISION" ("YEAR_MONTH");
CREATE INDEX "IDX_PRODUCT_COM__LIST_ID_AGENT" ON "K_PRODUCT_COMMISION" ("LIST_ID", "AGENT_ID");
CREATE INDEX "IDX_PRODUCT_COM__POLICY_ID" ON "K_PRODUCT_COMMISION" ("POLICY_ID");
CREATE INDEX "IDX_PROD_COMM__CHANGE_ID" ON "K_PRODUCT_COMMISION" ("CHANGE_ID");
CREATE INDEX "IDX_PROD_COMM__CHEQUE_CATE" ON "K_PRODUCT_COMMISION" ("CHEQUE_INDI", "AGENT_CATE");
CREATE INDEX "IDX_PROD_COMM__POLICY_CHG_ID" ON "K_PRODUCT_COMMISION" ("POLICY_CHG_ID");

-- for K_PRODUCTION_DETAIL
CREATE INDEX "IDX_PRODUCTION_DETAIL_CII" ON "K_PRODUCTION_DETAIL" ("COMM_ITEM_ID");
CREATE INDEX "IDX_PRODUCTION_DETAIL__AGGREG1" ON "K_PRODUCTION_DETAIL" ("AGGREGATION_ID", "PRODUCER_ID");
CREATE INDEX "IDX_PRODUCTION_DETAIL__POLICY1" ON "K_PRODUCTION_DETAIL" ("POLICY_CHG_ID", "PRODUCTION_ID");
CREATE INDEX "IDX_PRODUCTION_DETAIL__RELATED" ON "K_PRODUCTION_DETAIL" ("RELATED_ID");
CREATE INDEX "IDX_PRODUCTION_DETAIL__RESULT_" ON "K_PRODUCTION_DETAIL" ("RESULT_LIST_ID");
CREATE INDEX "IDX_PROD_DETAIL_YM_AG" ON "K_PRODUCTION_DETAIL" ("YEAR_MONTH", "PRODUCER_ID");
CREATE INDEX "IDX_PROD_DETAIL_YM_CH" ON "K_PRODUCTION_DETAIL" ("YEAR_MONTH", "CHANNEL_ORG_ID");
CREATE INDEX "IDX_PROD_DETAIL__AGENT_CHANNEL" ON "K_PRODUCTION_DETAIL" ("AGENT_CATE", "CHANNEL_ORG_ID");
CREATE INDEX "IDX_PROD_DETAIL__POLICY_ID" ON "K_PRODUCTION_DETAIL" ("POLICY_ID");
CREATE INDEX "IDX_PROD_DETAIL__PRODUCER_ID" ON "K_PRODUCTION_DETAIL" ("PRODUCER_ID", "EFFECTIVE_DATE");
CREATE INDEX "IDX_PROD_DETIAL__CHEQUE_CATE" ON "K_PRODUCTION_DETAIL" ("CHEQUE_INDI", "AGENT_CATE");
CREATE INDEX "IDX_PROD_DETIAL__ITEM_ID" ON "K_PRODUCTION_DETAIL" ("ITEM_ID");

-- for K_SUPPL_LOG_SYNC
CREATE INDEX "IDX_SUPPL_LOG_SYNC_1" ON "K_SUPPL_LOG_SYNC" ("INSERT_TIME");
