BEGIN
	execute immediate 'CREATE INDEX "IDX_CONTRACT_PRODUCT_L__LAST_C" ON "K_CONTRACT_PRODUCT_LOG" ("LAST_CMT_FLG", "ITEM_ID")';
	execute immediate 'CREATE INDEX "IDX_CONTRACT_PRODUCT_L__L_POL" ON "K_CONTRACT_PRODUCT_LOG" ("LAST_CMT_FLG", "POLICY_ID")';
	execute immediate 'CREATE INDEX "IDX_CONTR_PRD_LOG_MAST_WAIVE" ON "K_CONTRACT_PRODUCT_LOG" ("MASTER_ID", "WAIVER")';
	execute immediate 'ALTER TABLE "K_CONTRACT_PRODUCT_LOG" ADD CONSTRAINT "UNI_CONTRACT_PRODUCT_LOG__ID" UNIQUE ("POLICY_CHG_ID", "ITEM_ID", "LOG_TYPE")';
END;	