BEGIN
	execute immediate 'CREATE INDEX "IDX_CONT_EXTE_CX__OPER_TYPE" ON "K_CONTRACT_EXTEND_CX" ("CHANGE_ID", "OPER_TYPE")';
	execute immediate 'CREATE INDEX "I_CONTRACT_EXTEND_CX__LOG_ID" ON "K_CONTRACT_EXTEND_CX" ("LOG_ID")';
END;