BEGIN
	execute immediate 'ALTER TABLE "K_CONTRACT_PRODUCT_LOG" ADD CONSTRAINT "K_CONTRACT_PRODUCT_LOG_X" PRIMARY KEY ("LOG_ID")';
	execute immediate 'CREATE UNIQUE INDEX "K_CONTRACT_PRODUCT_LOG_ETL" ON "K_CONTRACT_PRODUCT_LOG" ("SCN","COMMIT_SCN","ROW_ID")');
END;	
