BEGIN
	execute immediate 'ALTER TABLE "K_JBPM_VARIABLEINSTANCE" ADD CONSTRAINT "K_JBPM_VARIABLEINSTANCE_X" PRIMARY KEY ("ID_")';
	execute immediate 'CREATE UNIQUE INDEX "K_JBPM_VARIABLEINSTANCE_ETL" ON "K_JBPM_VARIABLEINSTANCE" ("SCN","COMMIT_SCN","ROW_ID")');
END;
