BEGIN
	execute immediate 'ALTER TABLE "K_PRODUCTION_DETAIL" ADD CONSTRAINT "K_PRODUCTION_DETAIL_X" PRIMARY KEY ("DETAIL_ID")';
	execute immediate 'CREATE UNIQUE INDEX "K_PRODUCTION_DETAIL_ETL" ON "K_PRODUCTION_DETAIL" ("SCN","COMMIT_SCN","ROW_ID")');
END;	
