create table K_SUPPL_LOG_SYNC
(
	RS_ID VARCHAR2(32 BYTE) , 
	SSN NUMBER(19,0), 
	SCN NUMBER(19,0), 
	REMARK VARCHAR2(500 BYTE),
	INSERT_TIME NUMBER(19,0),
	CONSTRAINT "PK_K_SUPPL_LOG_SYNC" PRIMARY KEY ("RS_ID", "SSN")
)
