SELECT
       MA.JOB_ID                          AS JOB_ID
      ,MA.POLICY_ID                       AS POLICY_ID
      ,MA.PAYCARD_INDI                    AS PAYCARD_INDI
      ,MA.LETTER_INDI                     AS LETTER_INDI
      ,MA.ACKLETTER_INDI                  AS ACKLETTER_INDI
      ,MA.PIS_INDI                        AS PIS_INDI
      ,MA.HEALTH_CARD_INDI                AS HEALTH_CARD_INDI
      ,MA.COVER_INDI                      AS COVER_INDI
      ,MA.SCHEDULE_INDI                   AS SCHEDULE_INDI
      ,MA.CLAUSE_INDI                     AS CLAUSE_INDI
      ,MA.ANNEXURE_INDI                   AS ANNEXURE_INDI
      ,MA.ENDORSE_INDI                    AS ENDORSE_INDI
      ,MA.EXCLUSION_INDI                  AS EXCLUSION_INDI
      ,MA.PRINT_CATEGORY                  AS PRINT_CATEGORY
      ,MA.PRINT_TYPE                      AS PRINT_TYPE
      ,MA.PRINT_COPYSET                   AS PRINT_COPYSET
      ,MA.PRINT_REASON                    AS PRINT_REASON
      ,MA.VALID_STATUS                    AS VALID_STATUS
      ,MA.PRINT_DATE                      AS PRINT_DATE
      ,MA.OPERATOR_ID                     AS OPERATOR_ID
      ,MA.INSERT_TIME                     AS INSERT_TIME
      ,MA.INSERTED_BY                     AS INSERTED_BY
      ,MA.INSERT_TIMESTAMP                AS INSERT_TIMESTAMP
      ,MA.UPDATED_BY                      AS UPDATED_BY
      ,MA.UPDATE_TIMESTAMP                AS UPDATE_TIMESTAMP
      ,MA.PREMVOUCHER_INDI                AS PREMVOUCHER_INDI
      ,MA.ARCHIVE_ID                      AS ARCHIVE_ID
      ,MA.UPDATE_TIME                     AS UPDATE_TIME
      ,MA.JOB_TYPE_DESC                   AS JOB_TYPE_DESC
      ,MA.JOB_READY_DATE                  AS JOB_READY_DATE
      ,MA.CONTENT                         AS CONTENT
      ,MA.COPY                            AS COPY
      ,MA.ERROR_CODE                      AS ERROR_CODE
      ,MA.LANG_ID                         AS LANG_ID
      ,MA.CHANGE_ID                       AS CHANGE_ID
      ,MA.PRINT_COMP_INDI                 AS PRINT_COMP_INDI
