CREATE TABLE JBPM_VARIABLEINSTANCE_UPDATE
   (	
 ID_	NUMBER(19,0) NOT NULL,
CLASS_	CHAR(4 BYTE),
VERSION_	NUMBER(10,0),
NAME_	VARCHAR2(1020 BYTE),
CONVERTER_	CHAR(4 BYTE),
TOKEN_	NUMBER(19,0),
TOKENVARIABLEMAP_	NUMBER(19,0),
PROCESSINSTANCE_	NUMBER(19,0),
BYTEARRAYVALUE_	NUMBER(19,0),
DATEVALUE_	TIMESTAMP(6),
DOUBLEVALUE_	FLOAT,
LONGIDCLASS_	VARCHAR2(1020 BYTE),
LONGVALUE_	NUMBER(19,0),
STRINGIDCLASS_	VARCHAR2(1020 BYTE),
STRINGVALUE_	VARCHAR2(4000 BYTE),
TASKINSTANCE_	NUMBER(19,0),
SCN NUMBER(19,0),
ROW_ID VARCHAR2(18 BYTE)
)
